packages:
  - example/*
  - packages/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - msgpackr-extract
  - prisma
  - unrs-resolver

overrides:
  vite: ^8.0.0-beta.0
