// @generated by `pnpm fate generate`
import type { AppRouter, Comment, Post, User } from '@nkzw/fate-server/src/trpc/router.ts';
import { createTRPCProxyClient } from '@trpc/client';
import { inferRouterInputs, inferRouterOutputs } from '@trpc/server';
import { createClient, createTRPCTransport, mutation, root } from 'react-fate';

type TRPCClientType = ReturnType<typeof createTRPCProxyClient<AppRouter>>;
type RouterInputs = inferRouterInputs<AppRouter>;
type RouterOutputs = inferRouterOutputs<AppRouter>;

const mutations = {
  'comment.add': mutation<Comment, RouterInputs['comment']['add'], RouterOutputs['comment']['add']>(
    'Comment',
  ),
  'comment.delete': mutation<
    Comment,
    RouterInputs['comment']['delete'],
    RouterOutputs['comment']['delete']
  >('Comment'),
  'post.add': mutation<Post, RouterInputs['post']['add'], RouterOutputs['post']['add']>('Post'),
  'post.like': mutation<Post, RouterInputs['post']['like'], RouterOutputs['post']['like']>('Post'),
  'post.unlike': mutation<Post, RouterInputs['post']['unlike'], RouterOutputs['post']['unlike']>(
    'Post',
  ),
  'user.update': mutation<User, RouterInputs['user']['update'], RouterOutputs['user']['update']>(
    'User',
  ),
} as const;

const roots = {
  categories: root<RouterOutputs['category']['list']>('Category'),
  category: root<RouterOutputs['category']['byId']>('Category'),
  comment: root<RouterOutputs['comment']['byId']>('Comment'),
  commentSearch: root<RouterOutputs['comment']['search']>('Comment'),
  event: root<RouterOutputs['event']['byId']>('Event'),
  events: root<RouterOutputs['event']['list']>('Event'),
  post: root<RouterOutputs['post']['byId']>('Post'),
  posts: root<RouterOutputs['post']['list']>('Post'),
  viewer: root<RouterOutputs['user']['viewer']>('User'),
} as const;

type GeneratedClientMutations = typeof mutations;
type GeneratedClientRoots = typeof roots;

declare module 'react-fate' {
  interface ClientMutations extends GeneratedClientMutations {}
  interface ClientRoots extends GeneratedClientRoots {}
}

export const createFateClient = (options: {
  links: Parameters<typeof createTRPCProxyClient>[0]['links'];
}) => {
  const trpcClient = createTRPCProxyClient<AppRouter>(options);

  const trpcMutations = {
    'comment.add': (client: TRPCClientType) => client.comment.add.mutate,
    'comment.delete': (client: TRPCClientType) => client.comment.delete.mutate,
    'post.add': (client: TRPCClientType) => client.post.add.mutate,
    'post.like': (client: TRPCClientType) => client.post.like.mutate,
    'post.unlike': (client: TRPCClientType) => client.post.unlike.mutate,
    'user.update': (client: TRPCClientType) => client.user.update.mutate,
  } as const;

  return createClient({
    mutations,
    transport: createTRPCTransport<AppRouter, typeof trpcMutations>({
      byId: {
        Category:
          (client: TRPCClientType) =>
          ({
            args,
            ids,
            select,
          }: {
            args?: Record<string, unknown>;
            ids: Array<string | number>;
            select: Array<string>;
          }) =>
            client.category.byId.query({
              args,
              ids: ids.map(String),
              select,
            }),
        Comment:
          (client: TRPCClientType) =>
          ({
            args,
            ids,
            select,
          }: {
            args?: Record<string, unknown>;
            ids: Array<string | number>;
            select: Array<string>;
          }) =>
            client.comment.byId.query({
              args,
              ids: ids.map(String),
              select,
            }),
        Event:
          (client: TRPCClientType) =>
          ({
            args,
            ids,
            select,
          }: {
            args?: Record<string, unknown>;
            ids: Array<string | number>;
            select: Array<string>;
          }) =>
            client.event.byId.query({
              args,
              ids: ids.map(String),
              select,
            }),
        Post:
          (client: TRPCClientType) =>
          ({
            args,
            ids,
            select,
          }: {
            args?: Record<string, unknown>;
            ids: Array<string | number>;
            select: Array<string>;
          }) =>
            client.post.byId.query({
              args,
              ids: ids.map(String),
              select,
            }),
      },
      client: trpcClient,
      queries: {
        viewer: (client: TRPCClientType) => client.user.viewer.query,
      },
      lists: {
        categories: (client: TRPCClientType) => client.category.list.query,
        commentSearch: (client: TRPCClientType) => client.comment.search.query,
        events: (client: TRPCClientType) => client.event.list.query,
        posts: (client: TRPCClientType) => client.post.list.query,
      },
      mutations: trpcMutations,
    }),
    types: [
      {
        type: 'User',
      },
      {
        fields: {
          author: { type: 'User' },
          post: { type: 'Post' },
        },
        type: 'Comment',
      },
      {
        type: 'Tag',
      },
      {
        fields: {
          author: { type: 'User' },
          category: { type: 'Category' },
          comments: { listOf: 'Comment' },
          tags: { listOf: 'Tag' },
        },
        type: 'Post',
      },
      {
        fields: {
          posts: { listOf: 'Post' },
        },
        type: 'Category',
      },
      {
        fields: {
          user: { type: 'User' },
        },
        type: 'EventAttendee',
      },
      {
        fields: {
          attendees: { listOf: 'EventAttendee' },
          host: { type: 'User' },
        },
        type: 'Event',
      },
    ],
  });
};
